kind: pipeline
name: build-frontend
trigger:
  branch: main
  event:
    exclude:
      - tag
    include:
      - push
      - pull_request
type: kubernetes

steps:
  - commands:
      - echo hello world
      - ls
      - pwd
